### PR TITLE
change function call trim-string to string-trim. return value after mm-distroy-parts.

### PR DESCRIPTION
**Pull request by whudwl**

### CODE REVIEW

**Review by jeremy-compostella — COMMENTED** [review]
I took your changes into account. I added you signed-off to the ```notmuch: Support the `save-article-for-reply' callback``` patch.

**Comment by whudwl** [comment]
> I took your changes into account. I added you signed-off to the `` notmuch: Support the `save-article-for-reply' callback `` patch.

Hi Jeremy. Sorry, i'm very unfamiliar with github stuff. Not sure I was looking at the right thing. 
I saw in below file that function (trim-string ...) is still used and (mm-destroy-parts) is still the last statement of org-msg-save-article-for-reply-notmuch making it return nil. 
https://github.com/whudwl/org-msg/blob/61168184280fac8db2cc680c7f1b34347f53cb20/org-msg.el

**Comment by jeremy-compostella** [comment]
This is where you should look at:
https://github.com/jeremy-compostella/org-msg/blob/experimental/org-msg.el

**Comment by whudwl** [comment]
just pulled latest commit from experimental branch. it works perfectly now. thank you so much.

**Pull request closed without merging**
