### PR TITLE
Implement inline latex math as images

### LINKED ISSUE #28: Math in Emails
It is quite common in my line of work to send latex math expressions via email and expect the reader to do the rendering in their head. Given that org allows for inline latex math expressions as well as rendering them to inline images (which works out quite well in the preview) it should be fairly easy to attach those as inline parts of the message. This would be very very useful.

I believe the only missing part would be to check for referenced files in the `ltximg` folder and attach those to the mail before sending as the generation already happens and the preview of the mail renders perfectly.

### PR DESCRIPTION
**Pull request by mgttlinger**
Fixes #28

### CODE REVIEW

**Comment by jeremy-compostella** [comment]
Squash the two first patches and make a nice commit message.

**Comment by mgttlinger** [comment]
Ok, your implementation is much nicer and works nicely. One addition I would love is to also allow the same functionality for SVGs generated by `dvisvgm` which are generated into an `<object>` with the file reference in the `data` attribute. If I patch this path to the absolute path, the svg is sadly not included in the email. If you tell me where to look I can investigate how to make this work as well.

**Comment by jeremy-compostella** [comment]
Using `tex:dvisvgm` I saw that is created object to files.  But this files contains XML SVG code which can be easily use to replace the object tag.  See the latest patch on the experimental branch.  Let me know if it works for you.

**Comment by mgttlinger** [comment]
Thanks for the fast response times and implementing my suggestions that quickly! This works perfectly.

**Comment by jeremy-compostella** [comment]
FYI, I decided to not merge your changes about the `tex:` option because this is more like an end-user decision.  What matters is that `org-msg' handle the png and svg use cases fine. 
I pushed the patches to the master branch.

**Pull request closed without merging**
