### PR TITLE
Notmuch support

### LINKED ISSUE #18: support for notmuch
I heard about this mode from Using Emacs and am eager to try it.

I use notmuch to handle email in emacs.  I get a "Backend not found" message when I try to run activate org-msg-mode in a message buffer.

Have you tried enabling notmuch?

thanks!

### PR DESCRIPTION
**Pull request by obar**
Closes #18

### CODE REVIEW

**Comment by runekaagaard** [comment]
This works very nicely for me, thank you so much!

**Comment by runekaagaard** [comment]
@obar Do you have a fix to getting autocomplete in the To field working? I think it's broken in org-msg, but not in default notmuch compose.

**Comment by obar** [comment]
@runekaagaard I am currently using [goobook](https://gitlab.com/goobook/goobook) called from a shell script to query and cache Google Contacts for this. In my config:

```
(use-package notmuch-address
  :after notmuch
  :config
  (setq notmuch-address-command "/home/ori/bin/goocontactquery.sh")
  (setq notmuch-address-selection-function
        (lambda (prompt collection initial-input)
          (completing-read prompt (cons initial-input collection) nil t nil 'notmuch-address-history))))
```

With my `completing-read` taken care of by Helm and the `goocontactquery.sh` script:

```
script #!/bin/sh
goobook query "$*" | sed 's/\(.*\)\t\(.*\)\t.*/\2 \<\1\>/' | sed '/^$/d'
```

This is my solution to keep my phone contacts and email contacts combined. It's not org-msg related but I hope it helps!

**Comment by matheuristic** [comment]
@obar This works really nicely, but I noticed that "C-c C-k" (`org-msg-edit-kill-buffer`) does not work currently because `org-msg-edit-kill-buffer` (via `org-msg-mua-call`) attempts to call `org-msg-edit-kill-buffer-notmuch` which isn't defined so nothing happens.

Adding the following `defalias` fixes it (at least for me).
```
  (defalias 'org-msg-edit-kill-buffer-notmuch 'message-kill-buffer)
```

**Comment by obar** [comment]
Thanks @matheuristic! I had applied my changes which were older than 2d0540c when `message-kill-buffer` was split up. Will update this pull request.

**Comment by runekaagaard** [comment]
Hi @obar. An onexpected behaviour happens when the mail fails to send. Then the content is replaced with the html and you have to press undo in the mail buffer before resending.

**Comment by obar** [comment]
I suspect the same would occur for other mail clients. Perhaps this isn't a
blocker for the pull request but rather its own new issue for the project?

**Comment by runekaagaard** [comment]
Ahh, sry. Yes of course, you are right.

**Comment by jeremy-compostella** [comment]
> I suspect the same would occur for other mail clients. Perhaps this isn't a blocker for the pull request but rather its own new issue for the project?

Right.  Feel free to file an issue for this.

**Comment by jeremy-compostella** [comment]
Thanks for the contribution !

**Comment by obar** [comment]
@jeremy-compostella thank you for the very useful package!

**Pull request merged**
